Create TimeSync Header and Hardware Implementation
E-TRocketry/2024-Comp pull request #3
Opened 2024-12-11 01:19 UTC by Raghav-M-Daga

2024-12-12 23:13 UTC, pchou05 commented on Gimbalize/src/hardwareReader.cpp
> +
#include <MKRIMU.h>

2024-12-12 23:13 UTC, pchou05 commented on Gimbalize/src/hardwareReader.cpp
>  Adafruit_MPU6050 mpu;
delete

2024-12-13 22:19 UTC, namnik100 requested changes
Check issues for stuff to add as well

2024-12-13 22:19 UTC, namnik100 commented on Gimbalize/src/hardwareReader.cpp
> +  float reading_time = millis()
Missing semicolon

2024-12-13 22:19 UTC, namnik100 commented on Gimbalize/src/hardwareReader.cpp
> +    desired_time = millis()
missing semicolon

2024-12-13 22:19 UTC, namnik100 commented on Gimbalize/src/hardwareReader.cpp
> +    std::array<double, 3> BMP_interpolated_values = bmpTmeSync.getValuesAt(desired_time);
"bmpTmeSync" undefined

2024-12-13 22:19 UTC, namnik100 commented on Gimbalize/src/hardwareReader.cpp
> +    std::array<double, 3> MPU_interpolated_values = mpuTmeSync.getValuesAt(desired_time);
"mpuTmeSync" undefined

2024-12-13 22:19 UTC, namnik100 commented on Gimbalize/src/hardwareReader.cpp
> +    desired_time = millis()
"desired_time" never instantiated, made sure to do it outside try and unsigned

2024-12-13 22:19 UTC, namnik100 commented on Gimbalize/src/timeSync.h
> +    std::pair<std::pair<double, std::array<double, 3>>, std::pair<double, std::array<double, 3>>> getClosestReadings(double desired_time) const;
getClosestReadings not defined/implemented anywhere?

2024-12-13 22:19 UTC, namnik100 commented on Gimbalize/src/timeSync.h
> +    std::array<double, 3> getValuesAt(double desired_time) const;
No edge-case handling for when time is 0 for instance (will return null), cover all edge cases

2024-12-13 22:22 UTC, namnik100 commented on Gimbalize/src/hardwareReader.cpp
> +    std::array<double, 3> MPU_interpolated_values = mpuTmeSync.getValuesAt(desired_time);
You can also store millis() in a variable at beginning of loop and compare with last loop time (mb realized that cell timing wasn't that accurate)

2024-12-13 22:23 UTC, namnik100 commented
testing webhook ignore

2024-12-31 05:39 UTC, namnik100 reviewed
mpuTimeSync() and bmpTimeSynx() not defined
Include timesync.h dependencies in main

the interpolation is assuming that ull get a reading when u ask for it, like the sensor doesnt have to give a value at that time, make sure u throw an exception for this case like if(readings.empty)

delay(100) causes loop overruns use non-blocking logic like with millis()

there's thing i wanted to try call  rolling time window, so instead of using one desired_time specific like a range like 50 miliseconds from desired time, get all of those values, and find the average as the actual value

2024-12-31 20:12 UTC, closed without merging